---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fileshare
spec:
  rules:
  - host: fileshare.s<номер своего логина>.edu.slurm.io
    http:
      paths:
      - backend:
          serviceName: fileshare
          servicePort: 80
